use_frameworks!

platform :ios, '10.0'

target 'SDMovableCellCollectionView_Example' do
  pod 'SDMovableCellCollectionView', :path => '../'

  target 'SDMovableCellCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
